### ISSUE TITLE
Review for JOSS

### ISSUE THREAD

**Issue by fauxneticien** [marccanby/linguiphyr#15]
Hi @marccanby  —

Just completing my review for JOSS. Looks like Simon's review has covered quite a bit already so just some minor notes in a single issue:

1.  Permissions may not be sufficient
<img width="801" alt="Screenshot 2024-03-05 at 4 22 16 PM" src="https://github.com/marccanby/linguiphyr/assets/9938298/30b2666d-9272-471b-be27-6d3f27a9eaac">

I ran into the "Open a Mac app from an unidentified developer" issue when I went to click "Run PAUP*" later. You might want to specify people to right click and open the `paup` executable here to trigger the `Open a Mac app from an unidentified developer` warning here after installation, so R can call it later down the line.

2. Image broken in README:

<img width="856" alt="Screenshot 2024-03-05 at 4 20 53 PM" src="https://github.com/marccanby/linguiphyr/assets/9938298/46de09c9-ed1e-4c21-8084-6c92cfebb25e">

**Comment by marccanby** [comment]
Thanks for the great advice! I have taken care of both of these points, so I am closing the issue.
