### ISSUE TITLE
Some issues with references

### ISSUE THREAD

**Issue by SimonGreenhill** [marccanby/linguiphyr#2]
Incorrect formatting in reference list (check the bibtex {}):

- [ ] "Indo-european phylogenetics with r: "
- [ ] "indo-european"

Other issues

- [ ] Herce and Cathcart is now published, update reference details

**Comment by marccanby** [comment]
I have now addressed all of these issues on the branch assigned to this issue.

**Comment by SimonGreenhill** [comment]
lovely, thanks
