### ISSUE TITLE
UI glitch

### ISSUE THREAD

**Issue by SimonGreenhill** [marccanby/linguiphyr#3]
Running the app on R v4.3.2 on OS X shows an odd GUI Glitch. I don't know if this is a Shiny issue or a linguiphyr issue.

<img width="468" alt="Screen Shot 2024-01-17 at 09 26 47" src="https://github.com/marccanby/linguiphyr/assets/220169/2b35f616-f7ba-4bfc-9de2-f5c500101315">

**Comment by marccanby** [comment]
This has been resolved: the overlapping tabs with sidebar no longer occurs.
