### ISSUE TITLE
browse -> upload step is confusing

### ISSUE THREAD

**Issue by SimonGreenhill** [marccanby/linguiphyr#4]
I loaded the example data using the Data Input tab, clicking "Browse" and choosing a file. This then said it was uploaded via a blue progress bar but nothing else happened until I clicked "Upload". 

I suggest either automatically triggering the "Upload" step once a file has been selected with "Browse", and perhaps renaming the "Upload" to "Process"

**Comment by marccanby** [comment]
Thanks for the feedback! I have fixed this as you recommend (by automatically triggering upload without hitting a separate button).
