### ISSUE TITLE
consider selectively silencing warnings rather than all of them.

### ISSUE THREAD

**Issue by SimonGreenhill** [marccanby/linguiphyr#6]
Brute-force silencing all warnings in `server.R` because of a noisy/problematic package is probably a bad idea as it'll make debugging harder in future.

Can you selectively suppress the calls that generate the warnings e.g.

```r
suppressWarnings({
   plotly::whatever()
})
```

**Comment by marccanby** [comment]
I have fixed this by silencing just the warning in the renderPlotly function. This is now pushed on the main branch. Hence, I am no longer silencing all warnings as I was before.

**Comment by SimonGreenhill** [comment]
great, thanks!
