### ISSUE TITLE
Implement tests

### ISSUE THREAD

**Issue by SimonGreenhill** [marccanby/linguiphyr#7]
Testing the UI is complicated but there are many internal functions that could do with testing e.g. everything in the utils_* files are eminently testable with `testthat` and this would provide useful sanity checks for the more complicated parts of the analysis

**Comment by marccanby** [comment]
Thank you for the suggestion! I have now added 43 tests for various functionalities, mostly in the utils_* files, as you suggest. As part of this work, I have also enabled continuous integration, which automatically runs all the tests as well as R CMD Check upon pushing code. Further, the main branch is now protected and requires pull requests, which can only be approved if all tests and R CMD Check succeed without errors or warnings. I have also added a contributions section to the README which explains that users may raise such pull requests if they wish to resolve a bug in an issue (or suggest a new feature).

**Comment by SimonGreenhill** [comment]
Wonderful, thanks @marccanby!
